### ISSUE TITLE
Docker and Unraid support

### ISSUE THREAD

**Issue by janeoa** [ShuchirJ/HCGateway#9]
Hello! I am interested in self-hosting and using ur solution but I prefer using the docker. I am not very skilled yet, so I want to try making a dockerfile for this project and that might be my first good issue :D 

What do you think?

**Comment by CoolCoderSJ** [comment]
Hi,

That's a great idea! Please let me know if you need any help. Once you're done, feel free to make a pull request and I'll add the Dockerfile to the repo.

**Comment by vaddisrinivas** [comment]
Added via [PR:16](https://github.com/CoolCoderSJ/HCGateway/pull/16) - kindly test and review
